# Generated by Django 4.2.2 on 2023-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_eat_pizzas', 'Can eat pizzas')],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('userMain.person',),
        ),
    ]
